name: Build Docker Image

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GGML_RUNTIME: ["cpu", "cublas"]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      uses : docker/build-push-action@v5
      env:
        GGML_RUNTIME: ${{ matrix.GGML_RUNTIME }}
      with:
        context: .
        file: ./src/Whippersnapper/Dockerfile
        push: true
        tags: ghcr.io/whippersnapper/whippersnapper:latest-${{ matrix.GGML_RUNTIME }}

        
        
