name: Build

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install GitVersion tool
      run: dotnet tool install -g GitVersion.Tool
    - name: Determine Version
      id: determine-version
      uses: gittools/actions/gitversion/execute@v0
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish windows-x64
      run: dotnet publish --configuration Release --output ./publish/windows-x64 --runtime win-x64 ./Whippersnapper/Whippersnapper.csproj

    - name: Zip windows-x64
      run: 7z a -tzip ./publish/windows-x64.zip ./publish/windows-x64

    - name: Publish linux-x64
      run: dotnet publish --configuration Release --output ./publish/linux-x64 --runtime linux-x64 ./Whippersnapper/Whippersnapper.csproj

    - name: Zip linux-x64
      run: 7z a -tzip ./publish/linux-x64.zip ./publish/linux-x64
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.determine-version.outputs.semver }}
        release_name: v${{ steps.determine-version.outputs.semver }}
        draft: false
        prerelease: false
    - name: Upload windows-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/windows-x64.zip
        asset_name: Whippersnapper-windows-x64.zip
        asset_content_type: application/zip
    - name: Upload linux-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/linux-x64.zip
        asset_name: Whippersnapper-linux-x64.zip
        asset_content_type: application/zip
     