name: Build

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install GitVersion tool
      run: dotnet tool install -g GitVersion.Tool
    - name: Determine Version
      id: determine-version
      uses: gittools/actions/gitversion/execute@v0

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.determine-version.outputs.semver }}
        release_name: v${{ steps.determine-version.outputs.semver }}
        draft: false
        prerelease: false
    - name: Build
      run: dotnet run --project ./src/Whippersnapper.Build -t PublishArtifacts
  
  
      